# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/.gitignore",
    "**/CNAME",
    ".gitattributes",
    ".gitignore",
    ".gitleaksignore",
    ".pdd",
    ".xcop",
    "README.md",
    "renovate.json",
    "src/test/resources/META-INF/MANIFEST.MF",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
